---
- name: Deploy Remnawave Node
  hosts: nodes
  become: true
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  vars:
    exposed_ports: "{{ node_exposed_ports }}"

  roles:
    - role: apt_update

    - role: common
      tags: [common]

    - role: remnanode
      tags: [remnanode]

