---
- name: Deploy Remnawave Panel
  hosts: panel
  become: true
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  vars:
    exposed_ports: "{{ panel_exposed_ports }}"

  roles:
    - role: common
      tags: [common]

    - role: caddy
      tags: [caddy]

    - role: remnawave
      tags: [remnawave]

  post_tasks:
    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          Deployment Complete!
          Panel Login: https://{{ domain }}/{{ caddy_custom_login_route }}
          Auth Portal: https://{{ domain }}/{{ caddy_custom_login_route }}/auth
          Subscription Page: https://{{ subscription_domain }}/<shortUuid>
